title: "職業実践2 PHP"
summary: "職業実践2で使用する教材・プログラムです。特に制限はないので何かあればPRください。"
topics: ["php", "laravel"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
  - chapter6
  - absence
  - chapter7
  - chapter8
